### PR TITLE
Pls. Fix this issue

### PR DESCRIPTION
**Pull request by RusselPlayz3422**
The textures are amazing! But i hate the fancy thing at the bottom left of the screen cause i can't press cancel on my phone pls. Move the fancy thing somewhere else cause i cant press rotate or cancel and it's making my game hard to controll..

### CODE REVIEW

**Comment by Xeloboyo** [comment]
Oop oki, lemme see if i can raise it a bit

**Comment by RusselPlayz3422** [comment]
A little more higher pls. So i can save schematics or cancel schematics.

**Comment by RusselPlayz3422** [comment]
A little more higher pls. So i can save schematics or cancel schematics.

**Comment by Xeloboyo** [comment]
Yup, uh button is moved for now on mobile, will put it in settimgs on next update

**Comment by RusselPlayz3422** [comment]
Awesome, thanks!

**Pull request closed without merging**
